/* 
 * Vacancy API
 *
 * Web API for AstralVacancy task project.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Результат синхронизации вакансий
    /// </summary>
    [DataContract]
    public partial class VacanciesUpdateResultDto :  IEquatable<VacanciesUpdateResultDto>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="VacanciesUpdateResultDto" /> class.
        /// </summary>
        /// <param name="AddedCount">Количество добавленных вакансий.</param>
        /// <param name="ErrorMessage">Сообщение об ошибке синхронизации.</param>
        public VacanciesUpdateResultDto(int? AddedCount = default(int?), string ErrorMessage = default(string))
        {
            this.AddedCount = AddedCount;
            this.ErrorMessage = ErrorMessage;
        }
        
        /// <summary>
        /// Количество добавленных вакансий
        /// </summary>
        /// <value>Количество добавленных вакансий</value>
        [DataMember(Name="addedCount", EmitDefaultValue=false)]
        public int? AddedCount { get; set; }

        /// <summary>
        /// Сообщение об ошибке синхронизации
        /// </summary>
        /// <value>Сообщение об ошибке синхронизации</value>
        [DataMember(Name="errorMessage", EmitDefaultValue=false)]
        public string ErrorMessage { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class VacanciesUpdateResultDto {\n");
            sb.Append("  AddedCount: ").Append(AddedCount).Append("\n");
            sb.Append("  ErrorMessage: ").Append(ErrorMessage).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as VacanciesUpdateResultDto);
        }

        /// <summary>
        /// Returns true if VacanciesUpdateResultDto instances are equal
        /// </summary>
        /// <param name="input">Instance of VacanciesUpdateResultDto to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(VacanciesUpdateResultDto input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.AddedCount == input.AddedCount ||
                    (this.AddedCount != null &&
                    this.AddedCount.Equals(input.AddedCount))
                ) && 
                (
                    this.ErrorMessage == input.ErrorMessage ||
                    (this.ErrorMessage != null &&
                    this.ErrorMessage.Equals(input.ErrorMessage))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.AddedCount != null)
                    hashCode = hashCode * 59 + this.AddedCount.GetHashCode();
                if (this.ErrorMessage != null)
                    hashCode = hashCode * 59 + this.ErrorMessage.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
